blog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from .views import *
from django.conf.urls.static import static

app_name = "blog"

urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('blog/', PostLV.as_view(), name='list'),
    path('blog/post/', PostLV.as_view(), name='list'),
    path('blog/post/<int:post_pk>', post_detail, name='detail'),

    # Comment
    path('<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('member/', include('member.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField("제목", max_length=100)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField("설명", max_length=200, blank=True)
    content = models.TextField("본문")
    photo = models.ImageField(blank=True, null=True)
    create_date = models.DateTimeField("작성시간", auto_now_add=True)
    modify_date = models.DateTimeField("수정시간", auto_now=True)

    def __str__(self):
        return f'Post (PK: {self.pk}, Author: {self.author.username})'

class PostImage(models.Model):
    property = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'content',
                    'placeholder': '댓글 달기...',
                }
            )
        }

    def clean_content(self):
        data = self.cleaned_data['content']
        errors = []
        if data == '':
            errors.append(forms.ValidationError('댓글 내용을 입력해주세요'))
        elif len(data) > 50:
            errors.append(forms.ValidationError('댓글 내용은 50자 이하로 입력해주세요'))
        if errors:
            raise forms.ValidationError(errors)
        return data

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .models import Post,PostImage,Comment
from .forms import CommentForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
class PostLV(ListView):
    model = Post
    # 어떤 데이터를 꺼내쓸래??
    context_object_name = 'post_list'

def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    property = Post.objects.get(pk=post_pk)
    image_list = property.images.all()
    comment_form = CommentForm()

    context = {
        'post' : post,
        'image_list' : image_list,
        'comment_form' : comment_form,
    }

    return render(request, 'blog/post_detail.html', context)

@login_required
def comment_create(request, post_pk):
    # GET 파라미터로 전달된 작업 완료 후 이동할 URL값
    next_path = request.GET.get('next')
    print(next_path)
    # 요청 메서드가 POST방식 일 때만 처리
    if request.method == 'POST':
        # Post인스턴스를 가져오거나 404 Response를 돌려줌
        post = get_object_or_404(Post, pk=post_pk)
        # request.POST데이터를 이용한 Bounded Form생성
        comment_form = CommentForm(request.POST)
        # 올바른 데이터가 Form인스턴스에 바인딩 되어있는지 유효성 검사
        if comment_form.is_valid():
            # 유효성 검사에 통과하면 ModelForm의 save()호출로 인스턴스 생성
            # DB에 저장하지 않고 인스턴스만 생성하기 위해 commit=False옵션 지정
            comment = comment_form.save(commit=False)
            # CommentForm에 지정되지 않았으나 필수요소인 author와 post속성을 지정
            comment.post = post
            comment.author = request.user
            # DB에 저장
            comment.save()

            # 성공 메시지를 다음 request의 결과로 전달하도록 지정
            messages.success(request, '댓글이 등록되었습니다')
        else:
            # 유효성 검사에 실패한 경우
            # 에러 목록을 순회하며 에러메시지를 작성, messages의 error레벨로 추가
            error_msg = '댓글 등록에 실패했습니다\n{}'.format(
                '\n'.join(
                    [f'- {error}'
                     for key, value in comment_form.errors.items()
                     for error in value]))
            messages.error(request, error_msg)

        # next paramater에 값이 담겨 온 경우, 해당 경로로 이동
        if next_path:
            return redirect(next_path)
        # next paramater가 빈 경우 post_list뷰로 이동
        return redirect('post:post_list')

templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
      <meta http-equiv="Content-Type" content="text/html" charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
      <meta name="HandheldFriendly" content="True" />
      <meta name="MobileOptimized" content="320" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title> 흥청망청 계모임 </title>
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
      <link rel="stylesheet" type="text/css" href="//cloud.typography.com/7604652/646302/css/fonts.css" />
  </head>
  <body>

  <header class="site-header">
    <div class="site-title-wrapper">
      <h1 class="site-title"><a href="/">흥청망청 블로그 </a></h1>
    </div>
    <div class="container" style="border-bottom: 1px solid #303030; text-align:center;">
      {% if user.is_authenticated %}
        {% if user.img_profile == ''%}
          <img src="/media/user/ben.jpg" class="main_img">
          {% else %}
          <a href="#"><img src={{user.img_profile.url}} class="main_img"></a>
        {% endif %}
        <a href="/member/logout"><img src="/static/images/logout.png" ></a>
      {% else %}
        <a href="/member/login"><img src="/static/images/login.png" ></a>
        <a href="/member/signup"><img src="/static/images/join.png" ></a>
      {% endif %}
    </div>
  </header>

  <div id="post-index" class="container">
  <header class="post-header">
    {% block header %}
    <h1 class="post-title"> Welcome<br/> 흥청망청</h1>
    <p class="deck">
      2019년 올해도 <a>흥청망청</a> 즐거운 계모임<br/>
      여기는 <a>흥청망청 공식 블로그</a>로 입니다.
    </p>
    {% endblock %}
  </header>

  {% block content %}
  {% endblock %}
  </div>
  <br/>
  <footer class="footer">
    <div class="container">
        <p class="footer-copyright">
          &copy; <a href="/admin">충배.</a>
          <br>Powered by <a href="http://djangoproject.com/" target="_blank">흥청망청</a>.
          <br>Theme based on <a href="https://github.com/roryg/ghostwriter" target="_blank">ghostwriter</a>
          by <a href="http://jollygoodthemes.com" target="_blank">JollyGoodThemes</a>.
        </p>
    </div>
  </footer>
  </body>
</html>

templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block header %}
<h1 class="post-title">{{post.title}}</h1>
<h2 class="post-date">
    <time datetime="{{ post.modify_date }}">{{ post.modify_date }}</time>
</h2>
<h2 class="post-write">작성자:{{ post.author }}</h2>
{% endblock %}
{% block content %}
 <div class="post-content">
   {% for postimage in image_list %}
     <img src="{{ postimage.image.url }}">
   {% endfor %}
   <br/>
{{post.content|linebreaksbr}}
 </div>
 <hr/>

 <div class="panel-body">
 		{% if post.comments.exists %}
 		<ul class="comment-list">
 			{% for comment in post.comments.all %}
 			<li class="comment" style="height:55px;">
        <span class="comment-image"><img src="{{ comment.author.img_profile.url }}" class="commant-user-image"></span>
 				<span class="comment-author">{{ comment.author.first_name }}</span>
 				<span class="comment-content">{{ comment.content }}</span>
 			</li>
 			{% endfor %}
 		</ul>
    {% endif %}
    {% if user.is_authenticated %}
      <form action="{% url 'blog:comment_create' post_pk=post.pk %}?next={% url 'blog:detail' post_pk=post.pk %}"
      method="POST"
      class="comment-form">
      {% csrf_token %}
      {{ comment_form.content }}
  		</form>
    {% endif %}
</div>

<!--   <div><img src="{{comment.author.img_profile.url}}" class="comment-image"></div>  -->

 <hr/>
<a href="/blog"> 처음으로 </a>

{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<ol class="post-list">
    {% for post in post_list %}
      <li class="post-stub">
        <a href="/blog/post/{{ post.pk }}" >
        <h4 class="post-stub-title">{{ post.title }}</h4>
        <time class="post-stub-date" datetime="{{ post.modify_date }}">{{ post.modify_date }}</time>
        </a>
      </li>
    {% endfor %}
</ol>
{% endblock %}